### ISSUE TITLE
Program Staff Directory C1 Alphabetical List Layout

### ISSUE THREAD

**Issue by JacobZwang** [hackforla/new-schools-today#40] opened 2020-02-10 00:42 UTC
### Overview
Program the visual design on the agreed-upon C1 layout.

### Action Items
- [ ] Static Nav Bar (Bottom)
- [ ] Put in place holder logo
- [ ] Create master container for staff containers
- [ ] Create containers for staff
- [ ] Add faces to staff containers
- [ ] Impliment name layout
- [ ] Implement Active navbar placeholder
- [ ] Search bar placeholder

### Resources/Instructions
Staff containers should scroll down until the last one is directly above the navbar for ease of reach.

**Comment by ethanh256** [comment] 2020-04-04 22:53
Duplicate of issue #43.

**Closed by ethanh256** 2020-04-04 22:53 UTC
